name: Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  package-mac:
    timeout-minutes: 30
    runs-on: macos-latest
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: npm install
        run: |
          npm install

      - name: Build and Package
        run: |
          npm run package:publish

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: release/build/mac-universal-x64-temp/your-app-file.zip
