name: Package and Upload

on:
  push:
    branches:
      - main

jobs:
  package-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run package:publish

      - name: Create a new tag
        id: create_tag
        run: |
          # 获取最新的提交 hash
          COMMIT_HASH=$(git rev-parse --short HEAD)
          # 创建新的标签，格式为 v1.0.0-commitHash
          TAG_NAME="v1.0.0-${COMMIT_HASH}"
          echo "Creating tag: $TAG_NAME"
          git tag $TAG_NAME
          git push origin $TAG_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.TONKEN }}

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: release/build/mac-universal-x64-temp/ElectronReact.dmg  # 请确认正确的文件路径
        env:
          GITHUB_TOKEN: ${{ secrets.TONKEN }}
